Fake type query
WizTonE/Ancestor pull request #8
Opened 2017-08-11 01:57 UTC by johnny5581

建立Fake Type之查詢，

2017-08-11 08:47 UTC, WizTonE commented on src/Ancestor/Ancestor.DataAccess/3.DAO/MSSqlDao.cs
> +    public class MSSqlDao : BaseAbstractDao, IDataAccessObject
Because BaseAbstractDao was already implement IDataAccessObject
So IDataAccessObject can be removed from here.

2017-08-11 08:49 UTC, WizTonE commented on src/Ancestor/Ancestor.DataAccess/3.DAO/OracleDao.cs
> +    public class OracleDao : BaseAbstractDao, IDataAccessObject
Because BaseAbstractDao was already implement IDataAccessObject
So IDataAccessObject can be removed from here.

2017-08-11 08:50 UTC, WizTonE requested changes
Because BaseAbstractDao was already implement IDataAccessObject
So IDataAccessObject can be removed from all DAOobjects

2017-08-11 08:54 UTC, WizTonE commented on src/Ancestor/Ancestor.DataAccess/3.DAO/LambdaExpressionHelper.cs
> +                        this.Write("TO_CHAR(");
Should check dbtype while using TO_CHAR
Becuase Oracle use TO_CHAR, but MSSQL use CHAR

2017-08-11 09:36 UTC, johnny5581 commented
fix, please review latest commit

2017-08-14 06:23 UTC, WizTonE reviewed
Good to go

2017-08-14 06:24 UTC, merged